[package]
name = "kctx"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
crossterm = "0.28.1"
kube = { version = "0.98.0", features = ["config"] }
k8s-openapi = { version = "0.24.0", features = ["v1_28"] }
serde_yaml = "0.9"